services:
  app:
    build: .
    image: ghcr.io/birabittoh/fixyoutube-go:main
    container_name: fixyoutube-go
    restart: unless-stopped
    env_file:
      - .env
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
        - NET_ADMIN
    env_file:
      - swag/swag.env
    volumes:
        - ./swag/fixyoutube.subdomain.conf:/config/nginx/proxy-confs/fixyoutube.subdomain.conf:ro
    ports:
        - 443:443
        - 80:80
    restart: unless-stopped
