services:
  app:
    build: .
    image: ghcr.io/birabittoh/fixyoutube-go:main
    container_name: fixyoutube-go
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - API_KEY=${API_KEY}
